name: unit test, static-analysis, E2E test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php_version: "8.5"
      - name: Install Dependencies
        run: composer install -q --no-ansi
      - name: Run PHPStan
        run: vendor/bin/phpstan analyse

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.5"
      - name: Install Dependencies
        run: composer install -q --no-ansi
      - name: Run PHPUnit
        run: vendor/bin/phpunit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install Dependencies
        run: npm ci
      - name: Run E2E Tests
        run: npm run test:e2e
